# Generated by Django 6.0.6 on 2026-06-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='points_calculated',
            field=models.BooleanField(default=False),
        ),
    ]
