# Generated by Django 6.0.6 on 2026-06-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_points_calculated'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[('PR', 'Primera Ronda'), ('SR', 'Segunda Ronda'), ('TR', 'Tercera Ronda'), ('OF', 'Octavos de Final'), ('CF', 'Cuartos de Final'), ('SF', 'Semifinal'), ('F', 'Final')], default='PR', max_length=2),
        ),
    ]
