# Generated by Django 6.0.6 on 2026-06-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[('PR', 'Primera Ronda'), ('SR', 'Segunda Ronda'), ('TR', 'Tercera Ronda'), ('DR', 'Dieciséisavos de Final'), ('OF', 'Octavos de Final'), ('CF', 'Cuartos de Final'), ('SF', 'Semifinal'), ('F', 'Final')], default='PR', max_length=2),
        ),
    ]
