# Generated by Django 6.0.6 on 2026-06-22 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_match_phase'),
        ('teams', '0002_team_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='last_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='live_minute',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='live_status',
            field=models.CharField(choices=[('NS', 'Por jugar'), ('LIVE', 'En juego'), ('HT', 'Descanso'), ('FT', 'Finalizado')], default='NS', max_length=5),
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('GOAL', 'Gol'), ('RED', 'Expulsion'), ('YELLOW', 'Amarilla'), ('OTHER', 'Otro')], default='OTHER', max_length=10)),
                ('player_name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='teams.team')),
            ],
            options={
                'ordering': ('minute', 'id'),
            },
        ),
    ]
