# Generated by Django 6.0.6 on 2026-06-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_match_api_football_fixture_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='football_data_match_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID externo del partido en football-data.org', null=True, unique=True),
        ),
    ]
