# Generated by Django 6.0.6 on 2026-06-25 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_match_finished_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='api_football_fixture_id',
        ),
        migrations.RemoveField(
            model_name='matchevent',
            name='api_football_event_key',
        ),
    ]
