# Generated by Django 6.0.6 on 2026-06-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_match_bracket_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_penalty_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Goles en tanda de penales del equipo visitante, si aplica.', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='football_data_winner',
            field=models.CharField(blank=True, default='', help_text='Ganador reportado por football-data.org: HOME_TEAM, AWAY_TEAM o DRAW.', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='home_penalty_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Goles en tanda de penales del equipo local, si aplica.', null=True),
        ),
    ]
