# Generated by Django 6.0.6 on 2026-06-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='country_code',
            field=models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 code (e.g., AR, BR)', max_length=2),
        ),
    ]
