# Generated by Django 6.0.6 on 2026-06-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_api_football_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='football_data_team_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID externo del equipo en football-data.org', null=True, unique=True),
        ),
    ]
