# Generated by Django 6.0.6 on 2026-06-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_football_data_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='group_code',
            field=models.CharField(blank=True, choices=[('A', 'Grupo A'), ('B', 'Grupo B'), ('C', 'Grupo C'), ('D', 'Grupo D'), ('E', 'Grupo E'), ('F', 'Grupo F'), ('G', 'Grupo G'), ('H', 'Grupo H'), ('I', 'Grupo I'), ('J', 'Grupo J'), ('K', 'Grupo K'), ('L', 'Grupo L')], db_index=True, default='', help_text='Grupo de primera ronda del Mundial 2026 (A-L).', max_length=1, verbose_name='grupo'),
        ),
    ]
