# Generated by Django 6.0.6 on 2026-06-25 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='api_football_team_id',
        ),
    ]
