# Generated by Django 6.0.6 on 2026-06-24 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_notifications_enabled',
            field=models.BooleanField(default=False, help_text='El usuario aceptó recibir recordatorios de pronósticos por WhatsApp.', verbose_name='recibir recordatorios por WhatsApp'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_opt_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_phone_number',
            field=models.CharField(blank=True, default='', help_text='Número en formato internacional, por ejemplo +573001234567.', max_length=20, verbose_name='WhatsApp'),
        ),
        migrations.CreateModel(
            name='WhatsAppReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField(db_index=True)),
                ('reminder_type', models.CharField(choices=[('morning_prediction', 'Recordatorio matutino de pronósticos')], default='morning_prediction', max_length=40)),
                ('phone_number', models.CharField(max_length=20)),
                ('pending_match_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('dry_run', 'Prueba'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('skipped', 'Omitido')], max_length=12)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=120)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_reminder_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'reminder_date', 'reminder_type'), name='unique_whatsapp_reminder_per_user_date_type')],
            },
        ),
    ]
