# Generated by Django 6.0.6 on 2026-06-26 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0008_team_flag_team_tla_populate_football_data_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopScorerStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_code', models.CharField(db_index=True, default='WC', max_length=20)),
                ('season', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('rank', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('external_key', models.CharField(max_length=180)),
                ('football_data_player_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('player_name', models.CharField(max_length=120)),
                ('team_name', models.CharField(blank=True, default='', max_length=120)),
                ('team_tla', models.CharField(blank=True, db_index=True, default='', max_length=3)),
                ('team_crest', models.URLField(blank=True, default='', max_length=255)),
                ('played_matches', models.PositiveSmallIntegerField(default=0)),
                ('goals', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('assists', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('penalties', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_scorer_standings', to='teams.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_scorer_standings', to='teams.team')),
            ],
            options={
                'ordering': ['rank', '-goals', 'player_name'],
                'constraints': [models.UniqueConstraint(fields=('competition_code', 'season', 'external_key'), name='unique_top_scorer_per_competition_season')],
            },
        ),
    ]
